"use strict";
var _a, _b, _c, _d;
Object.defineProperty(exports, "__esModule", { value: true });
_a = require('./lib/config'), exports.getConfig = _a.getConfig, exports.writeConfig = _a.writeConfig, exports.getPackage = _a.getPackage;
exports.database = require('./database');
exports.ModuleHandler = require('./ModuleHandler');
exports.logger = require('./logger');
exports.Locals = require('./lib/Locals').Locals;
exports.MongoSchema = require('./lib/MongoSchema');
exports.NotoresModule = require('./lib/NotoresModule');
_b = require('./lib/responseHandler'), exports.responseHandler = _b.responseHandler, exports.htmlResponder = _b.htmlResponder, exports.jsonResponder = _b.jsonResponder;
_c = require('./server'), exports.createServer = _c.createServer, exports.getServers = _c.getServers, exports.startServer = _c.startServer;
_d = require('./lib/routeUtils'), exports.handleActive = _d.handleActive, exports.updateHandleActive = _d.updateHandleActive, exports.routeWithHandle = _d.routeWithHandle, exports.middlewareForRouter = _d.middlewareForRouter, exports.addRouteToRegistry = _d.addRouteToRegistry, exports.getRegistry = _d.getRegistry, exports.checkEmptyParams = _d.checkEmptyParams, exports.checkParamIsObjectId = _d.checkParamIsObjectId, exports.checkInput = _d.checkInput;
