import { addConfigDefault, getConfig, getConfigDefaults, getDefaultConfig, getPackage, writeConfig } from "./lib/config";
import * as database from "./database";
import * as ModuleHandler from "./ModuleHandler";
import logger from './logger';
import { htmlResponder, jsonResponder, responseHandler } from "./lib/responseHandler";
import { createServer, getServers, startServer } from "./server";
import { addRouteToRegistry, checkEmptyParams, checkInput, checkParamIsObjectId, getRegistry, handleActive, middlewareForRouter, routeWithHandle, updateHandleActive } from "./lib/routeUtils";
import { isIErrorObject, isIModuleListing } from "./lib/helperFunctions";
declare const _default: {
    getConfig: typeof getConfig;
    writeConfig: typeof writeConfig;
    getPackage: typeof getPackage;
    addConfigDefault: typeof addConfigDefault;
    getConfigDefaults: typeof getConfigDefaults;
    getDefaultConfig: typeof getDefaultConfig;
    database: typeof database;
    ModuleHandler: typeof ModuleHandler;
    getModule: typeof ModuleHandler.getModule;
    loadModule: typeof ModuleHandler.loadModule;
    loadModules: typeof ModuleHandler.loadModules;
    getModulesList: typeof ModuleHandler.getModulesList;
    logger: typeof logger;
    Locals: any;
    MongoSchema: any;
    NotoresModule: any;
    responseHandler: typeof responseHandler;
    htmlResponder: typeof htmlResponder;
    jsonResponder: typeof jsonResponder;
    createServer: typeof createServer;
    getServers: typeof getServers;
    startServer: typeof startServer;
    handleActive: typeof handleActive;
    updateHandleActive: typeof updateHandleActive;
    routeWithHandle: typeof routeWithHandle;
    middlewareForRouter: typeof middlewareForRouter;
    addRouteToRegistry: typeof addRouteToRegistry;
    getRegistry: typeof getRegistry;
    checkEmptyParams: typeof checkEmptyParams;
    checkParamIsObjectId: typeof checkParamIsObjectId;
    checkInput: typeof checkInput;
    isIErrorObject: typeof isIErrorObject;
    isIModuleListing: typeof isIModuleListing;
};
export default _default;
//# sourceMappingURL=index.d.ts.map